"""rename department

Revision ID: 19b09f5ec9ae
Revises: 5b8818b2d416
Create Date: 2024-06-27 20:37:33.781990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19b09f5ec9ae'
down_revision = '5b8818b2d416'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###